=== wahad88/Cittadinanzattiva_tecweb/CittadinanzAttiva/resources/xml/xsd/news.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="root">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="news" minOccurs="0" maxOccurs="unbounded" >
					<xs:complexType>
						<xs:sequence>
							<xs:element name="titolo">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="50" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="data" type="xs:date" minOccurs="1" maxOccurs="1" />
							<xs:element name="ora" type="xs:string" minOccurs="1" maxOccurs="1" />
							<xs:element name="corpo" type="xs:string" minOccurs="1" maxOccurs="1" />
						</xs:sequence>
						<xs:attribute name="id" type="xs:integer" />
					</xs:complexType>
				</xs:element>
				<xs:element name ="check" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== wahad88/Cittadinanzattiva_tecweb/CittadinanzAttiva/resources/xml/news.xml
<?xml version="1.0"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/xsd/news.xsd">
  <news id="3">
    <titolo>Barra di ricerca per le segnalazioni</titolo>
    <data>2019-05-30</data>
    <ora>14:03</ora>
    <corpo>&#xC8; stata creata una barra per la ricerca delle segnalazioni. In questo modo &#xE8; molto pi&#xF9; semplice e veloce cercare una segnalazione in particolare.</corpo>
  </news>
  <news id="2">
    <titolo>Barra di ricerca per le News</titolo>
    <data>2019-04-05</data>
    <ora>21:29</ora>
    <corpo>&#xC8; stata aggiunta una barra di ricerca delle news</corpo>
  </news>
  <news id="1">
    <titolo>Lavori in corso</titolo>
    <data>2019-03-12</data>
    <ora>12:52</ora>
    <corpo>Ristrutturazione del sito in corso</corpo>
  </news>
  <check>Elemento di escape, controlla se il documento &#xE8; vuoto</check>
</root>
