=== wahad88/Cittadinanzattiva_tecweb/CittadinanzAttiva/resources/xml/xsd/prov.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="root">
	    <xs:complexType>
			<xs:sequence>
				<xs:element name="prov" maxOccurs="unbounded">
				    <xs:complexType mixed="true">
				        <xs:attribute name="id" type="xs:integer" use="required" />
				    </xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== wahad88/Cittadinanzattiva_tecweb/CittadinanzAttiva/resources/xml/provincie.xml
<?xml version="1.0"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/xsd/prov.xsd">
	<prov id="001">Torino</prov>
	<prov id="002">Vercelli</prov>
	<prov id="003">Novara</prov>
	<prov id="004">Cuneo</prov>
	<prov id="005">Asti</prov>
	<prov id="006">Alessandria</prov>
	<prov id="007">Aosta</prov>
	<prov id="008">Imperia</prov>
	<prov id="009">Savona</prov>
	<prov id="010">Genova</prov>
	<prov id="011">La Spezia</prov>
	<prov id="012">Varese</prov>
	<prov id="013">Como</prov>
	<prov id="014">Sondrio</prov>
	<prov id="015">Milano</prov>
	<prov id="016">Bergamo</prov>
	<prov id="017">Brescia</prov>
	<prov id="018">Pavia</prov>
	<prov id="019">Cremona</prov>
	<prov id="020">Mantova</prov>
	<prov id="021">Bolzano</prov>
	<prov id="022">Trento</prov>
	<prov id="023">Verona</prov>
	<prov id="024">Vicenza</prov>
	<prov id="025">Belluno</prov>
	<prov id="026">Treviso</prov>
	<prov id="027">Venezia</prov>
	<prov id="028">Padova</prov>
	<prov id="029">Rovigo</prov>
	<prov id="030">Udine</prov>
	<prov id="031">Gorizia</prov>
	<prov id="032">Trieste</prov>
	<prov id="033">Piacenza</prov>
	<prov id="034">Parma</prov>
	<prov id="035">Reggio Emilia</prov>
	<prov id="036">Modena</prov>
	<prov id="037">Bologna</prov>
	<prov id="038">Ferrara</prov>
	<prov id="039">Ravenna</prov>
	<prov id="040">Forli</prov>
	<prov id="041">Pesaro</prov>
	<prov id="042">Ancona</prov>
	<prov id="043">Macerata</prov>
	<prov id="044">Ascoli Piceno</prov>
	<prov id="045">Massa Carrara</prov>
	<prov id="046">Lucca</prov>
	<prov id="047">Pistoia</prov>
	<prov id="048">Firenze</prov>
	<prov id="049">Livorno</prov>
	<prov id="050">Pisa</prov>
	<prov id="051">Arezzo</prov>
	<prov id="052">Siena</prov>
	<prov id="053">Grosseto</prov>
	<prov id="054">Perugia</prov>
	<prov id="055">Terni</prov>
	<prov id="056">Viterbo</prov>
	<prov id="057">Rieti</prov>
	<prov id="058">Roma</prov>
	<prov id="059">Latina</prov>
	<prov id="060">Frosinone</prov>
	<prov id="061">Caserta</prov>
	<prov id="062">Benevento</prov>
	<prov id="063">Napoli</prov>
	<prov id="064">Avellino</prov>
	<prov id="065">Salerno</prov>
	<prov id="066">L'Aquila</prov>
	<prov id="067">Teramo</prov>
	<prov id="068">Pescara</prov>
	<prov id="069">Chieti</prov>
	<prov id="070">Campobasso</prov>
	<prov id="071">Foggia</prov>
	<prov id="072">Bari</prov>
	<prov id="073">Taranto</prov>
	<prov id="074">Brindisi</prov>
	<prov id="075">Lecce</prov>
	<prov id="076">Potenza</prov>
	<prov id="077">Matera</prov>
	<prov id="078">Cosenza</prov>
	<prov id="079">Catanzaro</prov>
	<prov id="080">Reggio Calabria</prov>
	<prov id="081">Trapani</prov>
	<prov id="082">Palermo</prov>
	<prov id="083">Messina</prov>
	<prov id="084">Agrigento</prov>
	<prov id="085">Caltanissetta</prov>
	<prov id="086">Enna</prov>
	<prov id="087">Catania</prov>
	<prov id="088">Ragusa</prov>
	<prov id="089">Siracusa</prov>
	<prov id="090">Sassari</prov>
	<prov id="091">Nuoro</prov>
	<prov id="092">Cagliari</prov>
	<prov id="093">Pordenone</prov>
	<prov id="094">Isernia</prov>
	<prov id="095">Oristano</prov>
	<prov id="096">Biella</prov>
	<prov id="097">Lecco</prov>
	<prov id="098">Lodi</prov>
	<prov id="099">Rimini</prov>
	<prov id="100">Prato</prov>
	<prov id="101">Crotone</prov>
	<prov id="102">Vibo Valentia</prov>
	<prov id="103">Verbano Cusio Ossola</prov>
</root>
